# Generated by Django 5.2.7 on 2025-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
