# Generated by Django 5.2.7 on 2025-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_user',
            field=models.ImageField(blank=True, default='user/profile-default.jpg', upload_to='user/'),
        ),
    ]
