# Generated by Django 5.2.7 on 2025-11-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
