# Generated by Django 5.2.7 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_comment_post_delete_blog_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weekly_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
