# Generated by Django 5.2.7 on 2025-12-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_weekly_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
