# Generated by Django 5.2.7 on 2025-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='slug_author',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
