# Generated by Django 5.2.7 on 2025-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_authorprofile_slug_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='slug_author',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
