# Generated by Django 5.2.7 on 2025-11-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_authorprofile_slug_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='followers',
        ),
    ]
